<?php
/**
 * Template Name: Pricing
 * @package TailPress
 */
get_header();
$cards=[
 ['title'=>'Tourism Suppliers','price'=>'0.75% – 2.8%','copy'=>'Success fee per booking with no fixed upfront or monthly TXA fee.','cta'=>'Apply Now','url'=>home_url('/apply-now/'),'featured'=>true],
 ['title'=>'Destinations','price'=>'Smart Destination Packages','copy'=>'Local, Regional and State packages for destination activation, content, trade tools and visitor experiences.','cta'=>'View Destination Pricing','url'=>home_url('/destinations/pricing/')],
 ['title'=>'Distributors','price'=>'Commercial Agreement','copy'=>'Commercial arrangements depend on distributor model, volume and agreed integration scope.','cta'=>'Become a Distributor','url'=>home_url('/distributors/')],
 ['title'=>'Booking Systems','price'=>'Partner Enquiry','copy'=>'Integration and commercial terms are handled through the booking-system partner pathway.','cta'=>'Partner Enquiry','url'=>home_url('/booking-systems/')],
];
?>
<article class="bg-white text-near-black [font-family:'Source_Sans_Pro',sans-serif]">
<section class="px-4 pb-8 pt-5 sm:pt-8 lg:px-5"><div class="relative mx-auto min-h-[470px] max-w-[1360px] overflow-hidden rounded-2xl bg-near-black sm:min-h-[520px] lg:min-h-[560px]"><div class="absolute inset-0 bg-[radial-gradient(circle_at_80%_20%,rgba(212,43,43,.38),transparent_34%),linear-gradient(135deg,#1a1a1a,#2a2a2a)]"></div><div class="relative z-10 flex min-h-[470px] items-center px-5 py-12 sm:min-h-[520px] sm:px-7 sm:py-14 lg:min-h-[560px] lg:px-8 lg:py-16"><div class="max-w-[780px]"><p class="inline-flex rounded-lg bg-brand px-4 py-2 text-xs font-bold text-white sm:text-sm">PRICING</p><h1 class="mt-5 text-[2rem] font-semibold leading-[1.08] text-white sm:text-5xl lg:leading-[56px]">A pricing model for every TXA pathway</h1><p class="mt-5 max-w-[680px] text-base font-semibold leading-7 text-white/90 sm:text-lg sm:leading-[30px]">Suppliers, destinations, distributors and booking-system partners connect to TXA in different ways. Choose the pathway that matches your organisation.</p><div class="mt-7 flex flex-col gap-3 sm:flex-row sm:gap-4"><a href="<?php echo esc_url(home_url('/apply-now/')); ?>" class="inline-flex min-h-11 w-full items-center justify-center rounded-lg bg-white px-6 py-3 text-center text-base font-bold text-brand !no-underline sm:w-auto sm:px-8 sm:text-lg">Apply Now</a><a href="<?php echo esc_url(home_url('/request-demo/')); ?>" class="inline-flex min-h-11 w-full items-center justify-center rounded-lg border border-white px-6 py-3 text-center text-base font-bold text-white !no-underline sm:w-auto sm:px-8 sm:text-lg">Request Demo</a></div></div></div></div></section>
<section class="px-4 py-10 sm:py-12 lg:px-16 lg:py-20"><div class="mx-auto max-w-[1312px]"><div class="text-center"><p class="text-xs uppercase text-brand sm:text-sm">Choose your pathway</p><h2 class="mt-3 text-2xl font-bold leading-8 text-[#151c27] sm:text-3xl lg:text-4xl">TXA pricing by audience</h2><p class="mx-auto mt-4 max-w-[700px] text-base leading-7 text-mid-gray sm:text-lg sm:leading-8">Each audience has a different commercial model, so pricing stays aligned to the value and role of each connection.</p></div><div class="mt-10 grid gap-4 sm:mt-12 sm:grid-cols-2 sm:gap-6 lg:grid-cols-4 lg:mt-14"><?php foreach($cards as $card): ?><article class="relative flex min-h-0 flex-col rounded-2xl <?php echo !empty($card['featured'])?'border-2 border-brand shadow-xl':'border border-[#dfc0ba]/30'; ?> bg-white p-6 sm:min-h-[360px] sm:rounded-3xl sm:p-8"><?php if(!empty($card['featured'])): ?><span class="absolute -top-3 left-1/2 -translate-x-1/2 whitespace-nowrap rounded-full bg-brand px-3 py-1 text-[10px] uppercase tracking-wide text-white sm:px-4 sm:text-xs">MOST COMMON</span><?php endif; ?><p class="text-xs font-bold uppercase text-brand sm:text-sm"><?php echo esc_html($card['title']); ?></p><h3 class="mt-5 text-2xl font-bold leading-tight text-[#151c27] sm:mt-7 sm:text-3xl"><?php echo esc_html($card['price']); ?></h3><p class="mt-4 text-sm leading-6 text-mid-gray sm:mt-5"><?php echo esc_html($card['copy']); ?></p><a href="<?php echo esc_url($card['url']); ?>" class="mt-6 inline-flex min-h-11 items-center justify-center rounded-lg <?php echo !empty($card['featured'])?'bg-brand text-white':'border border-brand text-brand'; ?> px-5 py-3 text-center text-sm font-bold !no-underline sm:mt-auto"><?php echo esc_html($card['cta']); ?></a></article><?php endforeach; ?></div></div></section>
<section class="bg-surface px-4 py-10 sm:py-12 lg:px-16 lg:py-14"><div class="mx-auto grid max-w-[1312px] gap-7 rounded-2xl bg-white p-6 sm:p-8 lg:grid-cols-[1fr_.9fr] lg:items-center lg:gap-10 lg:p-12"><div><p class="text-xs uppercase text-brand sm:text-sm">Supplier pricing</p><h2 class="mt-3 text-2xl font-bold leading-8 text-[#151c27] sm:text-3xl">No booking, no fee</h2><p class="mt-4 max-w-[650px] text-sm leading-6 text-mid-gray sm:mt-5 sm:text-base sm:leading-7">For TXA-originated supplier bookings, the success-fee model means TXA is paid when a booking is generated. There are no fixed TXA subscription fees for suppliers under this model.</p><a href="<?php echo esc_url(home_url('/suppliers/')); ?>" class="mt-6 inline-flex min-h-11 w-full items-center justify-center rounded-lg bg-brand px-6 py-3 text-sm font-bold text-white !no-underline sm:mt-7 sm:w-auto sm:px-7">Explore Supplier Pathway</a></div><div class="rounded-2xl border border-line bg-surface p-6 sm:p-8"><p class="text-xs uppercase text-mid-gray sm:text-sm">Success fee range</p><p class="mt-3 break-words text-4xl font-bold leading-none text-brand sm:text-5xl">0.75% – 2.8%</p><div class="mt-6 h-3 rounded-full bg-brand/15 sm:mt-7"><div class="h-3 w-7/12 rounded-full bg-brand"></div></div></div></div></section>
<section class="px-4 py-10 sm:py-12 lg:px-16 lg:py-14"><div class="mx-auto max-w-[1100px] rounded-2xl bg-brand px-5 py-9 text-center text-white sm:px-8 sm:py-12 lg:px-16"><h2 class="text-2xl font-bold leading-8 sm:text-3xl lg:text-4xl">Not sure which pricing pathway applies?</h2><p class="mx-auto mt-4 max-w-[660px] text-base leading-7 text-white/90 sm:text-lg sm:leading-8">Tell us what type of organisation you are and TXA can direct you to the right connection model.</p><a href="<?php echo esc_url(home_url('/contact/')); ?>" class="mt-6 inline-flex min-h-11 w-full items-center justify-center rounded-lg bg-white px-7 py-3 text-sm font-bold text-brand !no-underline sm:mt-7 sm:w-auto sm:px-8">Contact TXA</a></div></section>
</article>
<?php get_footer();
