<?php
/**
 * Template Name: Destination Trade Portal
 * @package TailPress
 */
get_header();
$benefits=[['Create an industry-facing destination hub','Give travel trade partners one destination-led place to discover local products and experiences.'],['Showcase connected inventory','Surface relevant tourism supply through a structured destination environment backed by TXA connectivity.'],['Support trade engagement','Make it easier for destination teams to present product, campaigns and destination information to trade audiences.'],['Extend destination reach','Use TXA infrastructure to support partnerships and distribution beyond consumer-facing channels.']];
?>
<article class="bg-white text-near-black [font-family:'Source_Sans_Pro',sans-serif]">
<section class="px-4 py-6 sm:py-8 lg:px-5"><div class="relative mx-auto min-h-[460px] max-w-[1360px] overflow-hidden rounded-2xl sm:min-h-[520px] lg:min-h-[560px]"><img src="https://images.unsplash.com/photo-1527631746610-bca00a040d60?auto=format&fit=crop&w=2200&q=85" alt="Travel trade partners exploring a destination" class="absolute inset-0 h-full w-full object-cover"><div class="absolute inset-0 bg-near-black/60 sm:bg-near-black/50"></div><div class="relative z-10 flex min-h-[460px] items-center px-6 py-14 sm:min-h-[520px] sm:px-8 sm:py-16 lg:min-h-[560px]"><div class="max-w-[760px]"><p class="inline-flex rounded-lg bg-brand px-4 py-2 text-xs font-bold text-white sm:text-sm">SMART DESTINATION</p><h1 class="mt-4 text-3xl font-semibold leading-[1.1] text-white sm:mt-5 sm:text-5xl lg:leading-[56px]">TXA Trade Portal</h1><p class="mt-4 max-w-[680px] text-base font-semibold leading-7 text-white sm:mt-5 sm:text-lg sm:leading-[30px]">Give travel trade partners a destination-led gateway to discover local tourism products, destination content and connected inventory in one industry-facing experience.</p><a href="<?php echo esc_url(home_url('/request-demo/')); ?>" class="mt-6 inline-flex min-h-12 w-full items-center justify-center rounded-lg bg-white px-6 py-3 text-base font-bold text-brand !no-underline sm:mt-7 sm:w-auto sm:px-8 sm:text-lg">Request Demo</a></div></div></div></section>
<section class="px-4 py-12 sm:py-14 lg:px-16 lg:py-20"><div class="mx-auto max-w-[1312px]"><p class="text-xs uppercase text-brand sm:text-sm">Trade activation</p><h2 class="mt-3 max-w-[760px] text-3xl font-bold leading-tight text-[#151c27] lg:text-4xl">A destination-owned entry point for the travel trade</h2><p class="mt-4 max-w-[820px] text-base leading-7 text-mid-gray sm:mt-5 sm:text-lg sm:leading-8">TXA Trade Portal helps destinations package industry-facing information and connected tourism supply into a focused experience for distributors, wholesalers, agents and trade partners.</p><div class="mt-8 grid gap-5 sm:mt-10 md:grid-cols-2 md:gap-6"><?php foreach($benefits as $item): ?><article class="rounded-2xl border border-[#dfc0ba]/30 bg-white p-6 shadow-sm sm:p-8"><span class="flex size-10 items-center justify-center rounded-lg bg-brand-tint font-bold text-brand">↗</span><h3 class="mt-5 text-xl font-semibold text-[#151c27]"><?php echo esc_html($item[0]); ?></h3><p class="mt-3 text-sm leading-6 text-mid-gray sm:text-base sm:leading-7"><?php echo esc_html($item[1]); ?></p></article><?php endforeach; ?></div></div></section>
<section class="bg-brand px-4 py-12 text-white sm:py-14 lg:px-16"><div class="mx-auto grid max-w-[1280px] gap-8 lg:grid-cols-[1fr_.9fr] lg:items-center lg:gap-10"><div><h2 class="text-3xl font-bold leading-tight lg:text-4xl">Connect destination storytelling with trade-ready product</h2><p class="mt-4 max-w-[660px] text-base leading-7 text-white/90 sm:mt-5 sm:text-lg sm:leading-8">Create a more useful trade experience by combining destination context with connected local supply, without building a separate technology stack from scratch.</p></div><div class="grid grid-cols-1 gap-3 sm:grid-cols-2 sm:gap-4"><?php foreach(['Destination content','Connected products','Trade campaigns','Partner access'] as $label): ?><div class="rounded-xl border border-white/20 bg-white/10 p-5 text-sm font-semibold sm:p-6 sm:text-base"><?php echo esc_html($label); ?></div><?php endforeach; ?></div></div></section>
<section class="px-4 py-12 sm:py-14 lg:px-16"><div class="mx-auto max-w-[1000px] text-center"><h2 class="text-3xl font-bold leading-tight text-[#151c27] lg:text-4xl">Build a stronger trade pathway for your destination</h2><p class="mx-auto mt-4 max-w-[680px] text-base leading-7 text-mid-gray sm:text-lg sm:leading-8">Talk to TXA about adding a Trade Portal to your Smart Destination package.</p><a href="<?php echo esc_url(home_url('/request-demo/')); ?>" class="mt-6 inline-flex min-h-12 w-full items-center justify-center rounded-lg bg-brand px-6 py-3 font-bold text-white !no-underline sm:mt-7 sm:w-auto sm:px-8">Request a Smart Destination Demo</a></div></section>
</article>
<?php get_footer();
