<?php
/**
 * Template Name: Destination Virtual Concierge
 * @package TailPress
 */
get_header();
$benefits=[['Always-on visitor guidance','Give visitors a simple digital entry point to discover places, experiences and relevant destination information.'],['Use destination-owned content','Power recommendations from your own structured destination content and connected tourism ecosystem.'],['Support discovery in context','Place concierge experiences across destination websites, campaigns, visitor centres, accommodation and partner touchpoints.'],['Create clearer pathways to action','Help visitors move from inspiration toward connected products, experiences and booking opportunities.']];
?>
<article class="bg-white text-near-black [font-family:'Source_Sans_Pro',sans-serif]">
<section class="px-4 py-8 lg:px-5"><div class="relative mx-auto min-h-[560px] max-w-[1360px] overflow-hidden rounded-2xl"><img src="https://images.unsplash.com/photo-1526772662000-3f88f10405ff?auto=format&fit=crop&w=2200&q=85" alt="Visitor exploring a destination with digital guidance" class="absolute inset-0 h-full w-full object-cover"><div class="absolute inset-0 bg-near-black/48"></div><div class="relative z-10 flex min-h-[560px] items-center px-6 py-16 lg:px-8"><div class="max-w-[760px]"><p class="inline-flex rounded-lg bg-brand px-4 py-2 text-sm font-bold text-white">SMART DESTINATION</p><h1 class="mt-5 text-4xl font-semibold leading-tight text-white sm:text-5xl lg:leading-[56px]">Virtual Concierge</h1><p class="mt-5 max-w-[680px] text-lg font-semibold leading-[30px] text-white">Help visitors discover what to do, where to go and what to book through destination-led digital concierge experiences powered by your own tourism content.</p><a href="<?php echo esc_url(home_url('/request-demo/')); ?>" class="mt-7 inline-flex rounded-lg bg-white px-8 py-3 text-lg font-bold text-brand !no-underline">Request Demo</a></div></div></div></section>
<section class="px-4 py-14 lg:px-16 lg:py-20"><div class="mx-auto max-w-[1312px]"><p class="text-sm uppercase text-brand">Visitor experience</p><h2 class="mt-3 max-w-[800px] text-3xl font-bold text-[#151c27] lg:text-4xl">Put destination knowledge closer to the visitor</h2><p class="mt-5 max-w-[820px] text-lg leading-8 text-mid-gray">Virtual Concierge turns your structured destination content into practical visitor guidance that can be activated across multiple touchpoints before and during a trip.</p><div class="mt-10 grid gap-6 md:grid-cols-2"><?php foreach($benefits as $item): ?><article class="rounded-2xl border border-[#dfc0ba]/30 bg-white p-8 shadow-sm"><span class="flex size-10 items-center justify-center rounded-full bg-brand text-white">?</span><h3 class="mt-5 text-xl font-semibold text-[#151c27]"><?php echo esc_html($item[0]); ?></h3><p class="mt-3 leading-7 text-mid-gray"><?php echo esc_html($item[1]); ?></p></article><?php endforeach; ?></div></div></section>
<section class="bg-surface px-4 py-14 lg:px-16"><div class="mx-auto grid max-w-[1312px] gap-12 rounded-2xl bg-white p-8 lg:grid-cols-[1fr_.9fr] lg:items-center lg:p-12"><div><p class="text-sm uppercase text-brand">Flexible activation</p><h2 class="mt-3 text-3xl font-bold text-[#151c27]">Use it where visitors already are</h2><p class="mt-5 text-base leading-7 text-mid-gray">Create concierge initiatives for different visitor contexts without duplicating your destination content foundation.</p><div class="mt-8 grid gap-4 sm:grid-cols-2"><?php foreach(['Destination website','Visitor information centres','Accommodation partners','Campaign landing pages','Events and precincts','QR and mobile touchpoints'] as $label): ?><div class="rounded-lg border border-line bg-surface p-5 font-semibold text-[#151c27]"><?php echo esc_html($label); ?></div><?php endforeach; ?></div></div><div class="rounded-2xl bg-near-black p-6 text-white shadow-xl"><p class="text-sm uppercase text-white/50">Virtual Concierge</p><h3 class="mt-3 text-2xl font-semibold">What would you like to discover?</h3><div class="mt-6 space-y-3"><?php foreach(['Things to do nearby','Food & drink','Family experiences','Bookable tours'] as $label): ?><div class="rounded-lg bg-white/10 px-5 py-4"><?php echo esc_html($label); ?><span class="float-right text-brand">→</span></div><?php endforeach; ?></div></div></div></section>
<section class="px-4 py-14 lg:px-16"><div class="mx-auto max-w-[1000px] text-center"><h2 class="text-3xl font-bold text-[#151c27] lg:text-4xl">Create a more helpful digital visitor experience</h2><p class="mx-auto mt-4 max-w-[680px] text-lg leading-8 text-mid-gray">Talk to TXA about Virtual Concierge initiatives for your destination.</p><a href="<?php echo esc_url(home_url('/destinations/pricing/')); ?>" class="mt-7 inline-flex rounded-lg bg-brand px-8 py-3 font-bold text-white !no-underline">View Destination Packages</a></div></section>
</article>
<?php get_footer();
