<?php
/**
 * Template Name: Destination Trade Portal
 * @package TailPress
 */
get_header();
$benefits=[['Create an industry-facing destination hub','Give travel trade partners one destination-led place to discover local products and experiences.'],['Showcase connected inventory','Surface relevant tourism supply through a structured destination environment backed by TXA connectivity.'],['Support trade engagement','Make it easier for destination teams to present product, campaigns and destination information to trade audiences.'],['Extend destination reach','Use TXA infrastructure to support partnerships and distribution beyond consumer-facing channels.']];
?>
<article class="bg-white text-near-black [font-family:'Source_Sans_Pro',sans-serif]">
<section class="px-4 py-8 lg:px-5"><div class="relative mx-auto min-h-[560px] max-w-[1360px] overflow-hidden rounded-2xl"><img src="https://images.unsplash.com/photo-1527631746610-bca00a040d60?auto=format&fit=crop&w=2200&q=85" alt="Travel trade partners exploring a destination" class="absolute inset-0 h-full w-full object-cover"><div class="absolute inset-0 bg-near-black/50"></div><div class="relative z-10 flex min-h-[560px] items-center px-6 py-16 lg:px-8"><div class="max-w-[760px]"><p class="inline-flex rounded-lg bg-brand px-4 py-2 text-sm font-bold text-white">SMART DESTINATION</p><h1 class="mt-5 text-4xl font-semibold leading-tight text-white sm:text-5xl lg:leading-[56px]">TXA Trade Portal</h1><p class="mt-5 max-w-[680px] text-lg font-semibold leading-[30px] text-white">Give travel trade partners a destination-led gateway to discover local tourism products, destination content and connected inventory in one industry-facing experience.</p><a href="<?php echo esc_url(home_url('/request-demo/')); ?>" class="mt-7 inline-flex rounded-lg bg-white px-8 py-3 text-lg font-bold text-brand !no-underline">Request Demo</a></div></div></div></section>
<section class="px-4 py-14 lg:px-16 lg:py-20"><div class="mx-auto max-w-[1312px]"><p class="text-sm uppercase text-brand">Trade activation</p><h2 class="mt-3 max-w-[760px] text-3xl font-bold text-[#151c27] lg:text-4xl">A destination-owned entry point for the travel trade</h2><p class="mt-5 max-w-[820px] text-lg leading-8 text-mid-gray">TXA Trade Portal helps destinations package industry-facing information and connected tourism supply into a focused experience for distributors, wholesalers, agents and trade partners.</p><div class="mt-10 grid gap-6 md:grid-cols-2"><?php foreach($benefits as $item): ?><article class="rounded-2xl border border-[#dfc0ba]/30 bg-white p-8 shadow-sm"><span class="flex size-10 items-center justify-center rounded-lg bg-brand-tint font-bold text-brand">↗</span><h3 class="mt-5 text-xl font-semibold text-[#151c27]"><?php echo esc_html($item[0]); ?></h3><p class="mt-3 leading-7 text-mid-gray"><?php echo esc_html($item[1]); ?></p></article><?php endforeach; ?></div></div></section>
<section class="bg-brand px-4 py-14 text-white lg:px-16"><div class="mx-auto grid max-w-[1280px] gap-10 lg:grid-cols-[1fr_.9fr] lg:items-center"><div><h2 class="text-3xl font-bold lg:text-4xl">Connect destination storytelling with trade-ready product</h2><p class="mt-5 max-w-[660px] text-lg leading-8 text-white/90">Create a more useful trade experience by combining destination context with connected local supply, without building a separate technology stack from scratch.</p></div><div class="grid gap-4 sm:grid-cols-2"><?php foreach(['Destination content','Connected products','Trade campaigns','Partner access'] as $label): ?><div class="rounded-xl border border-white/20 bg-white/10 p-6 font-semibold"><?php echo esc_html($label); ?></div><?php endforeach; ?></div></div></section>
<section class="px-4 py-14 lg:px-16"><div class="mx-auto max-w-[1000px] text-center"><h2 class="text-3xl font-bold text-[#151c27] lg:text-4xl">Build a stronger trade pathway for your destination</h2><p class="mx-auto mt-4 max-w-[680px] text-lg leading-8 text-mid-gray">Talk to TXA about adding a Trade Portal to your Smart Destination package.</p><a href="<?php echo esc_url(home_url('/request-demo/')); ?>" class="mt-7 inline-flex rounded-lg bg-brand px-8 py-3 font-bold text-white !no-underline">Request a Smart Destination Demo</a></div></section>
</article>
<?php get_footer();
