<?php
/**
 * Template Name: Destination Microsite Campaigns
 * @package TailPress
 */
get_header();
$uses=[['Tactical campaigns','Launch focused destination campaigns around seasons, events, themes or target markets without rebuilding your main website.'],['Connected product discovery','Bring relevant tourism products and experiences into each campaign so inspiration can lead toward action.'],['Faster activation','Reuse destination content and connected supply to shorten the path from campaign idea to live digital experience.'],['Measurable outcomes','Use a more connected campaign environment that can support clearer engagement and booking performance measurement.']];
?>
<article class="bg-white text-near-black [font-family:'Source_Sans_Pro',sans-serif]">
<section class="px-4 py-6 sm:py-8 lg:px-5"><div class="relative mx-auto min-h-[460px] max-w-[1360px] overflow-hidden rounded-2xl sm:min-h-[520px] lg:min-h-[560px]"><img src="https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=2200&q=85" alt="Destination campaign experience" class="absolute inset-0 h-full w-full object-cover"><div class="absolute inset-0 bg-near-black/58 sm:bg-near-black/48"></div><div class="relative z-10 flex min-h-[460px] items-center px-6 py-14 sm:min-h-[520px] sm:px-8 sm:py-16 lg:min-h-[560px]"><div class="max-w-[760px]"><p class="inline-flex rounded-lg bg-brand px-4 py-2 text-xs font-bold text-white sm:text-sm">SMART DESTINATION</p><h1 class="mt-4 text-3xl font-semibold leading-[1.1] text-white sm:mt-5 sm:text-5xl lg:leading-[56px]">Microsite Campaigns</h1><p class="mt-4 max-w-[680px] text-base font-semibold leading-7 text-white sm:mt-5 sm:text-lg sm:leading-[30px]">Create tactical destination microsites that combine campaign storytelling, local experiences and connected tourism products in a focused digital journey.</p><a href="<?php echo esc_url(home_url('/request-demo/')); ?>" class="mt-6 inline-flex min-h-12 w-full items-center justify-center rounded-lg bg-white px-6 py-3 text-base font-bold text-brand !no-underline sm:mt-7 sm:w-auto sm:px-8 sm:text-lg">Request Demo</a></div></div></div></section>
<section class="px-4 py-12 sm:py-14 lg:px-16 lg:py-20"><div class="mx-auto max-w-[1312px]"><p class="text-xs uppercase text-brand sm:text-sm">Campaign activation</p><h2 class="mt-3 max-w-[780px] text-3xl font-bold leading-tight text-[#151c27] lg:text-4xl">Create campaign experiences without creating another platform</h2><p class="mt-4 max-w-[820px] text-base leading-7 text-mid-gray sm:mt-5 sm:text-lg sm:leading-8">TXA Microsite Campaigns let destinations activate focused marketing initiatives using the same destination content and connected tourism ecosystem that supports the wider Smart Destination platform.</p><div class="mt-8 grid gap-5 sm:mt-10 md:grid-cols-2 xl:grid-cols-4 xl:gap-6"><?php foreach($uses as $item): ?><article class="rounded-2xl border border-[#dfc0ba]/30 bg-white p-6 shadow-sm sm:p-8"><span class="flex size-10 items-center justify-center rounded-lg bg-brand-tint font-bold text-brand">+</span><h3 class="mt-5 text-xl font-semibold text-[#151c27]"><?php echo esc_html($item[0]); ?></h3><p class="mt-3 text-sm leading-6 text-mid-gray"><?php echo esc_html($item[1]); ?></p></article><?php endforeach; ?></div></div></section>
<section class="bg-surface px-4 py-12 sm:py-14 lg:px-16"><div class="mx-auto grid max-w-[1312px] gap-8 rounded-2xl bg-white p-6 sm:p-8 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:gap-10 lg:p-12"><div><p class="text-xs uppercase text-brand sm:text-sm">One reusable ecosystem</p><h2 class="mt-3 text-3xl font-bold leading-tight text-[#151c27]">Build once, activate for different campaigns</h2><p class="mt-4 text-base leading-7 text-mid-gray sm:mt-5">Use the same destination content foundation for seasonal campaigns, themed journeys, event promotion, regional partnerships and tactical market activity.</p><a href="<?php echo esc_url(home_url('/destinations/pricing/')); ?>" class="mt-6 inline-flex min-h-12 w-full items-center justify-center rounded-lg border border-brand px-6 py-3 font-bold text-brand !no-underline sm:mt-7 sm:w-auto sm:px-7">View Destination Packages</a></div><div class="grid grid-cols-1 gap-3 sm:grid-cols-2 sm:gap-4"><?php foreach(['Seasonal campaign','Food & drink trail','Events & festivals','Partner promotion'] as $label): ?><div class="rounded-xl bg-surface p-5 sm:p-7"><p class="text-xs uppercase text-brand sm:text-sm">Campaign</p><p class="mt-2 text-lg font-semibold text-[#151c27] sm:text-xl"><?php echo esc_html($label); ?></p></div><?php endforeach; ?></div></div></section>
</article>
<?php get_footer();
