<?php
/**
 * Template Name: Destination Microsite Campaigns
 * @package TailPress
 */
get_header();
$uses=[['Tactical campaigns','Launch focused destination campaigns around seasons, events, themes or target markets without rebuilding your main website.'],['Connected product discovery','Bring relevant tourism products and experiences into each campaign so inspiration can lead toward action.'],['Faster activation','Reuse destination content and connected supply to shorten the path from campaign idea to live digital experience.'],['Measurable outcomes','Use a more connected campaign environment that can support clearer engagement and booking performance measurement.']];
?>
<article class="bg-white text-near-black [font-family:'Source_Sans_Pro',sans-serif]">
<section class="px-4 py-8 lg:px-5"><div class="relative mx-auto min-h-[560px] max-w-[1360px] overflow-hidden rounded-2xl"><img src="https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=2200&q=85" alt="Destination campaign experience" class="absolute inset-0 h-full w-full object-cover"><div class="absolute inset-0 bg-near-black/48"></div><div class="relative z-10 flex min-h-[560px] items-center px-6 py-16 lg:px-8"><div class="max-w-[760px]"><p class="inline-flex rounded-lg bg-brand px-4 py-2 text-sm font-bold text-white">SMART DESTINATION</p><h1 class="mt-5 text-4xl font-semibold leading-tight text-white sm:text-5xl lg:leading-[56px]">Microsite Campaigns</h1><p class="mt-5 max-w-[680px] text-lg font-semibold leading-[30px] text-white">Create tactical destination microsites that combine campaign storytelling, local experiences and connected tourism products in a focused digital journey.</p><a href="<?php echo esc_url(home_url('/request-demo/')); ?>" class="mt-7 inline-flex rounded-lg bg-white px-8 py-3 text-lg font-bold text-brand !no-underline">Request Demo</a></div></div></div></section>
<section class="px-4 py-14 lg:px-16 lg:py-20"><div class="mx-auto max-w-[1312px]"><p class="text-sm uppercase text-brand">Campaign activation</p><h2 class="mt-3 max-w-[780px] text-3xl font-bold text-[#151c27] lg:text-4xl">Create campaign experiences without creating another platform</h2><p class="mt-5 max-w-[820px] text-lg leading-8 text-mid-gray">TXA Microsite Campaigns let destinations activate focused marketing initiatives using the same destination content and connected tourism ecosystem that supports the wider Smart Destination platform.</p><div class="mt-10 grid gap-6 md:grid-cols-2 xl:grid-cols-4"><?php foreach($uses as $item): ?><article class="rounded-2xl border border-[#dfc0ba]/30 bg-white p-8 shadow-sm"><span class="flex size-10 items-center justify-center rounded-lg bg-brand-tint font-bold text-brand">+</span><h3 class="mt-5 text-xl font-semibold text-[#151c27]"><?php echo esc_html($item[0]); ?></h3><p class="mt-3 text-sm leading-6 text-mid-gray"><?php echo esc_html($item[1]); ?></p></article><?php endforeach; ?></div></div></section>
<section class="bg-surface px-4 py-14 lg:px-16"><div class="mx-auto grid max-w-[1312px] gap-10 rounded-2xl bg-white p-8 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:p-12"><div><p class="text-sm uppercase text-brand">One reusable ecosystem</p><h2 class="mt-3 text-3xl font-bold text-[#151c27]">Build once, activate for different campaigns</h2><p class="mt-5 text-base leading-7 text-mid-gray">Use the same destination content foundation for seasonal campaigns, themed journeys, event promotion, regional partnerships and tactical market activity.</p><a href="<?php echo esc_url(home_url('/destinations/pricing/')); ?>" class="mt-7 inline-flex rounded-lg border border-brand px-7 py-3 font-bold text-brand !no-underline">View Destination Packages</a></div><div class="grid gap-4 sm:grid-cols-2"><?php foreach(['Seasonal campaign','Food & drink trail','Events & festivals','Partner promotion'] as $label): ?><div class="rounded-xl bg-surface p-7"><p class="text-sm uppercase text-brand">Campaign</p><p class="mt-2 text-xl font-semibold text-[#151c27]"><?php echo esc_html($label); ?></p></div><?php endforeach; ?></div></div></section>
</article>
<?php get_footer();
