<?php
/**
 * Template Name: Data & Insights
 * @package TailPress
 */
get_header();
$insights = [
 ['title'=>'See demand and booking activity','copy'=>'Bring destination and booking activity into one view so teams can understand what visitors are engaging with and what converts.'],
 ['title'=>'Measure campaign performance','copy'=>'Connect destination activity with product discovery and booking outcomes to understand which initiatives are working.'],
 ['title'=>'Understand local supply','copy'=>'Track the depth, coverage and digital readiness of tourism products across your destination.'],
 ['title'=>'Make better decisions','copy'=>'Use practical destination intelligence to prioritise supplier activation, campaigns and future investment.'],
];
$metrics = ['Connected supply','Product discovery','Booking activity','Campaign performance'];
?>
<article class="bg-white text-near-black [font-family:'Source_Sans_Pro',sans-serif]">
<section class="px-4 py-8 lg:px-5"><div class="relative mx-auto min-h-[560px] max-w-[1360px] overflow-hidden rounded-2xl bg-near-black"><img src="https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=2200&q=85" alt="Tourism data and analytics dashboard" class="absolute inset-0 h-full w-full object-cover"><div class="absolute inset-0 bg-near-black/55"></div><div class="relative z-10 flex min-h-[560px] items-center px-6 py-16 lg:px-8"><div class="max-w-[760px]"><p class="inline-flex rounded-lg bg-brand px-4 py-2 text-sm font-bold text-white">DATA &amp; INSIGHTS</p><h1 class="mt-5 [font-family:'Hanken_Grotesk',sans-serif] text-4xl font-semibold leading-tight text-white sm:text-5xl lg:leading-[56px]">Turn tourism activity into destination intelligence</h1><p class="mt-5 max-w-[680px] text-lg font-semibold leading-[30px] text-white">TXA helps destinations understand connected supply, digital engagement and booking activity so teams can make better decisions with clearer evidence.</p><a href="<?php echo esc_url(home_url('/request-demo/')); ?>" class="mt-7 inline-flex rounded-lg bg-white px-8 py-3 text-lg font-bold text-brand !no-underline">Request Demo</a></div></div></div></section>
<section class="px-4 py-14 lg:px-16 lg:py-20"><div class="mx-auto max-w-[1312px]"><p class="text-sm uppercase text-brand">Destination intelligence</p><h2 class="mt-3 max-w-[760px] [font-family:'Hanken_Grotesk',sans-serif] text-3xl font-bold leading-tight text-[#151c27] lg:text-4xl">See what is happening across your digital visitor economy</h2><p class="mt-5 max-w-[780px] text-lg leading-8 text-mid-gray">TXA connects the infrastructure behind tourism distribution with practical reporting. That gives destination teams a stronger view of supply, engagement and commercial outcomes.</p><div class="mt-10 grid gap-6 md:grid-cols-2 xl:grid-cols-4"><?php foreach($insights as $item): ?><article class="rounded-2xl border border-[#dfc0ba]/30 bg-white p-8 shadow-sm"><span class="flex size-11 items-center justify-center rounded-lg bg-brand-tint text-xl font-bold text-brand">+</span><h3 class="mt-6 text-xl font-semibold text-[#151c27]"><?php echo esc_html($item['title']); ?></h3><p class="mt-3 text-sm leading-6 text-mid-gray"><?php echo esc_html($item['copy']); ?></p></article><?php endforeach; ?></div></div></section>
<section class="bg-surface px-4 py-14 lg:px-16 lg:py-20"><div class="mx-auto grid max-w-[1312px] gap-10 rounded-2xl bg-white p-8 shadow-sm lg:grid-cols-[1fr_1.05fr] lg:items-center lg:p-12"><div><p class="text-sm uppercase text-brand">One connected view</p><h2 class="mt-3 text-3xl font-bold text-[#151c27] lg:text-4xl">From supply activation to booking outcomes</h2><p class="mt-5 text-base leading-7 text-mid-gray">Understand how your digital assets and connected tourism products perform across the visitor journey, without creating another isolated reporting stack.</p><div class="mt-8 grid gap-4 sm:grid-cols-2"><?php foreach($metrics as $metric): ?><div class="rounded-lg border border-line bg-surface p-5 text-base font-semibold text-[#151c27]"><?php echo esc_html($metric); ?></div><?php endforeach; ?></div></div><div class="rounded-xl bg-near-black p-6 text-white shadow-xl"><div class="grid grid-cols-2 gap-4"><div class="rounded-lg bg-white/10 p-5"><p class="text-xs uppercase text-white/60">Supply</p><p class="mt-2 text-3xl font-bold">Live</p></div><div class="rounded-lg bg-white/10 p-5"><p class="text-xs uppercase text-white/60">Channels</p><p class="mt-2 text-3xl font-bold">Connected</p></div><div class="col-span-2 rounded-lg bg-white/10 p-5"><p class="text-xs uppercase text-white/60">Performance</p><div class="mt-6 flex h-32 items-end gap-3"><?php foreach([45,68,52,82,73,94] as $height): ?><span class="flex-1 rounded-t bg-brand" style="height:<?php echo esc_attr($height); ?>%"></span><?php endforeach; ?></div></div></div></div></div></section>
<section class="px-4 py-14 lg:px-16 lg:py-20"><div class="mx-auto max-w-[1100px] rounded-2xl bg-brand px-8 py-12 text-center text-white lg:px-16"><h2 class="text-3xl font-bold lg:text-4xl">Make your destination data more useful</h2><p class="mx-auto mt-4 max-w-[680px] text-lg leading-8 text-white/90">See how TXA can support a more connected, measurable visitor economy.</p><a href="<?php echo esc_url(home_url('/request-demo/')); ?>" class="mt-7 inline-flex rounded-lg bg-white px-8 py-3 font-bold text-brand !no-underline">Request a Smart Destination Demo</a></div></section>
</article>
<?php get_footer();
