<?php
/**
 * Template Name: Pricing
 * @package TailPress
 */
get_header();
$cards=[
 ['title'=>'Tourism Suppliers','price'=>'0.75% – 2.8%','copy'=>'Success fee per booking with no fixed upfront or monthly TXA fee.','cta'=>'Apply Now','url'=>home_url('/apply-now/'),'featured'=>true],
 ['title'=>'Destinations','price'=>'Smart Destination Packages','copy'=>'Local, Regional and State packages for destination activation, content, trade tools and visitor experiences.','cta'=>'View Destination Pricing','url'=>home_url('/destinations/pricing/')],
 ['title'=>'Distributors','price'=>'Commercial Agreement','copy'=>'Commercial arrangements depend on distributor model, volume and agreed integration scope.','cta'=>'Become a Distributor','url'=>home_url('/distributors/')],
 ['title'=>'Booking Systems','price'=>'Partner Enquiry','copy'=>'Integration and commercial terms are handled through the booking-system partner pathway.','cta'=>'Partner Enquiry','url'=>home_url('/booking-systems/')],
];
?>
<article class="bg-white text-near-black [font-family:'Source_Sans_Pro',sans-serif]">
<section class="px-4 py-8 lg:px-5"><div class="relative mx-auto min-h-[560px] max-w-[1360px] overflow-hidden rounded-2xl bg-near-black"><div class="absolute inset-0 bg-[radial-gradient(circle_at_80%_20%,rgba(212,43,43,.38),transparent_34%),linear-gradient(135deg,#1a1a1a,#2a2a2a)]"></div><div class="relative z-10 flex min-h-[560px] items-center px-6 py-16 lg:px-8"><div class="max-w-[780px]"><p class="inline-flex rounded-lg bg-brand px-4 py-2 text-sm font-bold text-white">PRICING</p><h1 class="mt-5 text-4xl font-semibold leading-tight text-white sm:text-5xl lg:leading-[56px]">A pricing model for every TXA pathway</h1><p class="mt-5 max-w-[680px] text-lg font-semibold leading-[30px] text-white/90">Suppliers, destinations, distributors and booking-system partners connect to TXA in different ways. Choose the pathway that matches your organisation.</p><div class="mt-7 flex flex-col gap-4 sm:flex-row"><a href="<?php echo esc_url(home_url('/apply-now/')); ?>" class="rounded-lg bg-white px-8 py-3 text-center text-lg font-bold text-brand !no-underline">Apply Now</a><a href="<?php echo esc_url(home_url('/request-demo/')); ?>" class="rounded-lg border border-white px-8 py-3 text-center text-lg font-bold text-white !no-underline">Request Demo</a></div></div></div></div></section>
<section class="px-4 py-14 lg:px-16 lg:py-20"><div class="mx-auto max-w-[1312px]"><div class="text-center"><p class="text-sm uppercase text-brand">Choose your pathway</p><h2 class="mt-3 text-3xl font-bold text-[#151c27] lg:text-4xl">TXA pricing by audience</h2><p class="mx-auto mt-4 max-w-[700px] text-lg leading-8 text-mid-gray">Each audience has a different commercial model, so pricing stays aligned to the value and role of each connection.</p></div><div class="mt-14 grid gap-6 lg:grid-cols-4"><?php foreach($cards as $card): ?><article class="relative flex min-h-[390px] flex-col rounded-3xl <?php echo !empty($card['featured'])?'border-2 border-brand shadow-xl':'border border-[#dfc0ba]/30'; ?> bg-white p-8"><?php if(!empty($card['featured'])): ?><span class="absolute -top-3 left-1/2 -translate-x-1/2 rounded-full bg-brand px-4 py-1 text-xs uppercase tracking-wide text-white">MOST COMMON</span><?php endif; ?><p class="text-sm font-bold uppercase text-brand"><?php echo esc_html($card['title']); ?></p><h3 class="mt-7 text-3xl font-bold leading-tight text-[#151c27]"><?php echo esc_html($card['price']); ?></h3><p class="mt-5 text-sm leading-6 text-mid-gray"><?php echo esc_html($card['copy']); ?></p><a href="<?php echo esc_url($card['url']); ?>" class="mt-auto rounded-lg <?php echo !empty($card['featured'])?'bg-brand text-white':'border border-brand text-brand'; ?> px-5 py-3 text-center font-bold !no-underline"><?php echo esc_html($card['cta']); ?></a></article><?php endforeach; ?></div></div></section>
<section class="bg-surface px-4 py-14 lg:px-16"><div class="mx-auto grid max-w-[1312px] gap-10 rounded-2xl bg-white p-8 lg:grid-cols-[1fr_.9fr] lg:items-center lg:p-12"><div><p class="text-sm uppercase text-brand">Supplier pricing</p><h2 class="mt-3 text-3xl font-bold text-[#151c27]">No booking, no fee</h2><p class="mt-5 max-w-[650px] text-base leading-7 text-mid-gray">For TXA-originated supplier bookings, the success-fee model means TXA is paid when a booking is generated. There are no fixed TXA subscription fees for suppliers under this model.</p><a href="<?php echo esc_url(home_url('/suppliers/')); ?>" class="mt-7 inline-flex rounded-lg bg-brand px-7 py-3 font-bold text-white !no-underline">Explore Supplier Pathway</a></div><div class="rounded-2xl border border-line bg-surface p-8"><p class="text-sm uppercase text-mid-gray">Success fee range</p><p class="mt-3 text-5xl font-bold text-brand">0.75% – 2.8%</p><div class="mt-7 h-3 rounded-full bg-brand/15"><div class="h-3 w-7/12 rounded-full bg-brand"></div></div></div></div></section>
<section class="px-4 py-14 lg:px-16"><div class="mx-auto max-w-[1100px] rounded-2xl bg-brand px-8 py-12 text-center text-white lg:px-16"><h2 class="text-3xl font-bold lg:text-4xl">Not sure which pricing pathway applies?</h2><p class="mx-auto mt-4 max-w-[660px] text-lg leading-8 text-white/90">Tell us what type of organisation you are and TXA can direct you to the right connection model.</p><a href="<?php echo esc_url(home_url('/contact/')); ?>" class="mt-7 inline-flex rounded-lg bg-white px-8 py-3 font-bold text-brand !no-underline">Contact TXA</a></div></section>
</article>
<?php get_footer();
