<?php
/**
 * Template Name: Data & Insights
 * @package TailPress
 */
get_header();
$insights = [
 ['title'=>'See demand and booking activity','copy'=>'Bring destination and booking activity into one view so teams can understand what visitors are engaging with and what converts.'],
 ['title'=>'Measure campaign performance','copy'=>'Connect destination activity with product discovery and booking outcomes to understand which initiatives are working.'],
 ['title'=>'Understand local supply','copy'=>'Track the depth, coverage and digital readiness of tourism products across your destination.'],
 ['title'=>'Make better decisions','copy'=>'Use practical destination intelligence to prioritise supplier activation, campaigns and future investment.'],
];
$metrics = ['Connected supply','Product discovery','Booking activity','Campaign performance'];
?>
<article class="bg-white text-near-black [font-family:'Source_Sans_Pro',sans-serif]">
<section class="px-4 py-6 sm:py-8 lg:px-5"><div class="relative mx-auto min-h-[480px] max-w-[1360px] overflow-hidden rounded-2xl bg-near-black sm:min-h-[520px] lg:min-h-[560px]"><img src="https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=2200&q=85" alt="Tourism data and analytics dashboard" class="absolute inset-0 h-full w-full object-cover"><div class="absolute inset-0 bg-near-black/65 sm:bg-near-black/55"></div><div class="relative z-10 flex min-h-[480px] items-center px-6 py-14 sm:min-h-[520px] sm:px-8 sm:py-16 lg:min-h-[560px]"><div class="max-w-[760px]"><p class="inline-flex rounded-lg bg-brand px-4 py-2 text-xs font-bold text-white sm:text-sm">DATA &amp; INSIGHTS</p><h1 class="mt-4 [font-family:'Hanken_Grotesk',sans-serif] text-3xl font-semibold leading-[1.1] text-white sm:mt-5 sm:text-5xl lg:leading-[56px]">Turn tourism activity into destination intelligence</h1><p class="mt-4 max-w-[680px] text-base font-semibold leading-7 text-white sm:mt-5 sm:text-lg sm:leading-[30px]">TXA helps destinations understand connected supply, digital engagement and booking activity so teams can make better decisions with clearer evidence.</p><a href="<?php echo esc_url(home_url('/request-demo/')); ?>" class="mt-6 inline-flex min-h-12 w-full items-center justify-center rounded-lg bg-white px-6 py-3 text-base font-bold text-brand !no-underline sm:mt-7 sm:w-auto sm:px-8 sm:text-lg">Request Demo</a></div></div></div></section>
<section class="px-4 py-12 sm:py-14 lg:px-16 lg:py-20"><div class="mx-auto max-w-[1312px]"><p class="text-xs uppercase text-brand sm:text-sm">Destination intelligence</p><h2 class="mt-3 max-w-[760px] [font-family:'Hanken_Grotesk',sans-serif] text-3xl font-bold leading-tight text-[#151c27] lg:text-4xl">See what is happening across your digital visitor economy</h2><p class="mt-4 max-w-[780px] text-base leading-7 text-mid-gray sm:mt-5 sm:text-lg sm:leading-8">TXA connects the infrastructure behind tourism distribution with practical reporting. That gives destination teams a stronger view of supply, engagement and commercial outcomes.</p><div class="mt-8 grid gap-5 sm:mt-10 md:grid-cols-2 xl:grid-cols-4 xl:gap-6"><?php foreach($insights as $item): ?><article class="rounded-2xl border border-[#dfc0ba]/30 bg-white p-6 shadow-sm sm:p-8"><span class="flex size-10 items-center justify-center rounded-lg bg-brand-tint text-lg font-bold text-brand sm:size-11 sm:text-xl">+</span><h3 class="mt-5 text-xl font-semibold text-[#151c27] sm:mt-6"><?php echo esc_html($item['title']); ?></h3><p class="mt-3 text-sm leading-6 text-mid-gray"><?php echo esc_html($item['copy']); ?></p></article><?php endforeach; ?></div></div></section>
<section class="bg-surface px-4 py-12 sm:py-14 lg:px-16 lg:py-20"><div class="mx-auto grid max-w-[1312px] gap-8 rounded-2xl bg-white p-6 shadow-sm sm:p-8 lg:grid-cols-[1fr_1.05fr] lg:items-center lg:p-12"><div><p class="text-xs uppercase text-brand sm:text-sm">One connected view</p><h2 class="mt-3 text-3xl font-bold leading-tight text-[#151c27] lg:text-4xl">From supply activation to booking outcomes</h2><p class="mt-4 text-base leading-7 text-mid-gray sm:mt-5">Understand how your digital assets and connected tourism products perform across the visitor journey, without creating another isolated reporting stack.</p><div class="mt-6 grid gap-3 sm:mt-8 sm:grid-cols-2 sm:gap-4"><?php foreach($metrics as $metric): ?><div class="rounded-lg border border-line bg-surface p-4 text-sm font-semibold text-[#151c27] sm:p-5 sm:text-base"><?php echo esc_html($metric); ?></div><?php endforeach; ?></div></div><div class="rounded-xl bg-near-black p-4 text-white shadow-xl sm:p-6"><div class="grid grid-cols-2 gap-3 sm:gap-4"><div class="rounded-lg bg-white/10 p-4 sm:p-5"><p class="text-[10px] uppercase text-white/60 sm:text-xs">Supply</p><p class="mt-2 text-2xl font-bold sm:text-3xl">Live</p></div><div class="rounded-lg bg-white/10 p-4 sm:p-5"><p class="text-[10px] uppercase text-white/60 sm:text-xs">Channels</p><p class="mt-2 text-xl font-bold sm:text-3xl">Connected</p></div><div class="col-span-2 rounded-lg bg-white/10 p-4 sm:p-5"><p class="text-[10px] uppercase text-white/60 sm:text-xs">Performance</p><div class="mt-5 flex h-24 items-end gap-2 sm:mt-6 sm:h-32 sm:gap-3"><?php foreach([45,68,52,82,73,94] as $height): ?><span class="flex-1 rounded-t bg-brand" style="height:<?php echo esc_attr($height); ?>%"></span><?php endforeach; ?></div></div></div></div></div></section>
<section class="px-4 py-12 sm:py-14 lg:px-16 lg:py-20"><div class="mx-auto max-w-[1100px] rounded-2xl bg-brand px-6 py-10 text-center text-white sm:px-8 sm:py-12 lg:px-16"><h2 class="text-3xl font-bold leading-tight lg:text-4xl">Make your destination data more useful</h2><p class="mx-auto mt-4 max-w-[680px] text-base leading-7 text-white/90 sm:text-lg sm:leading-8">See how TXA can support a more connected, measurable visitor economy.</p><a href="<?php echo esc_url(home_url('/request-demo/')); ?>" class="mt-6 inline-flex min-h-12 w-full items-center justify-center rounded-lg bg-white px-6 py-3 font-bold text-brand !no-underline sm:mt-7 sm:w-auto sm:px-8">Request a Smart Destination Demo</a></div></section>
</article>
<?php get_footer();
