<?php
/**
 * Template Name: Destination Virtual Concierge
 * @package TailPress
 */
get_header();
$benefits=[['Always-on visitor guidance','Give visitors a simple digital entry point to discover places, experiences and relevant destination information.'],['Use destination-owned content','Power recommendations from your own structured destination content and connected tourism ecosystem.'],['Support discovery in context','Place concierge experiences across destination websites, campaigns, visitor centres, accommodation and partner touchpoints.'],['Create clearer pathways to action','Help visitors move from inspiration toward connected products, experiences and booking opportunities.']];
?>
<article class="bg-white text-near-black [font-family:'Source_Sans_Pro',sans-serif]">
<section class="px-4 py-6 sm:py-8 lg:px-16"><div class="relative mx-auto min-h-[460px] max-w-[1312px] overflow-hidden rounded-2xl sm:min-h-[520px] lg:min-h-[560px]"><img src="https://images.unsplash.com/photo-1526772662000-3f88f10405ff?auto=format&fit=crop&w=2200&q=85" alt="Visitor exploring a destination with digital guidance" class="absolute inset-0 h-full w-full object-cover"><div class="absolute inset-0 bg-near-black/58 sm:bg-near-black/48"></div><div class="relative z-10 flex min-h-[460px] items-center px-6 py-14 sm:min-h-[520px] sm:px-8 sm:py-16 lg:min-h-[560px]"><div class="max-w-[760px]"><p class="inline-flex rounded-lg bg-brand px-4 py-2 text-xs font-bold text-white sm:text-sm">SMART DESTINATION</p><h1 class="mt-4 text-3xl font-semibold leading-[1.1] text-white sm:mt-5 sm:text-5xl lg:leading-[56px]">Virtual Concierge</h1><p class="mt-4 max-w-[680px] text-base font-semibold leading-7 text-white sm:mt-5 sm:text-lg sm:leading-[30px]">Help visitors discover what to do, where to go and what to book through destination-led digital concierge experiences powered by your own tourism content.</p><a href="<?php echo esc_url(home_url('/request-demo/')); ?>" class="mt-6 inline-flex min-h-12 w-full items-center justify-center rounded-lg bg-white px-6 py-3 text-base font-bold text-brand !no-underline sm:mt-7 sm:w-auto sm:px-8 sm:text-lg">Request Demo</a></div></div></div></section>
<section class="px-4 py-12 sm:py-14 lg:px-16 lg:py-20"><div class="mx-auto max-w-[1312px]"><p class="text-xs uppercase text-brand sm:text-sm">Visitor experience</p><h2 class="mt-3 max-w-[800px] text-3xl font-bold leading-tight text-[#151c27] lg:text-4xl">Put destination knowledge closer to the visitor</h2><p class="mt-4 max-w-[820px] text-base leading-7 text-mid-gray sm:mt-5 sm:text-lg sm:leading-8">Virtual Concierge turns your structured destination content into practical visitor guidance that can be activated across multiple touchpoints before and during a trip.</p><div class="mt-8 grid gap-5 sm:mt-10 md:grid-cols-2 md:gap-6"><?php foreach($benefits as $item): ?><article class="rounded-2xl border border-[#dfc0ba]/30 bg-white p-6 shadow-sm sm:p-8"><span class="flex size-10 items-center justify-center rounded-full bg-brand text-white">?</span><h3 class="mt-5 text-xl font-semibold text-[#151c27]"><?php echo esc_html($item[0]); ?></h3><p class="mt-3 text-sm leading-6 text-mid-gray sm:text-base sm:leading-7"><?php echo esc_html($item[1]); ?></p></article><?php endforeach; ?></div></div></section>
<section class="bg-surface px-4 py-12 sm:py-14 lg:px-16"><div class="mx-auto grid max-w-[1312px] gap-8 rounded-2xl bg-white p-6 sm:p-8 lg:grid-cols-[1fr_.9fr] lg:items-center lg:gap-12 lg:p-12"><div><p class="text-xs uppercase text-brand sm:text-sm">Flexible activation</p><h2 class="mt-3 text-3xl font-bold leading-tight text-[#151c27]">Use it where visitors already are</h2><p class="mt-4 text-base leading-7 text-mid-gray sm:mt-5">Create concierge initiatives for different visitor contexts without duplicating your destination content foundation.</p><div class="mt-6 grid gap-3 sm:mt-8 sm:grid-cols-2 sm:gap-4"><?php foreach(['Destination website','Visitor information centres','Accommodation partners','Campaign landing pages','Events and precincts','QR and mobile touchpoints'] as $label): ?><div class="rounded-lg border border-line bg-surface p-4 text-sm font-semibold text-[#151c27] sm:p-5 sm:text-base"><?php echo esc_html($label); ?></div><?php endforeach; ?></div></div><div class="rounded-2xl bg-near-black p-5 text-white shadow-xl sm:p-6"><p class="text-xs uppercase text-white/50 sm:text-sm">Virtual Concierge</p><h3 class="mt-3 text-2xl font-semibold leading-tight">What would you like to discover?</h3><div class="mt-5 space-y-3 sm:mt-6"><?php foreach(['Things to do nearby','Food & drink','Family experiences','Bookable tours'] as $label): ?><div class="flex items-center justify-between gap-3 rounded-lg bg-white/10 px-4 py-3 text-sm sm:px-5 sm:py-4 sm:text-base"><span><?php echo esc_html($label); ?></span><span class="shrink-0 text-brand">→</span></div><?php endforeach; ?></div></div></div></section>
<section class="px-4 py-12 sm:py-14 lg:px-16"><div class="mx-auto max-w-[1000px] text-center"><h2 class="text-3xl font-bold leading-tight text-[#151c27] lg:text-4xl">Create a more helpful digital visitor experience</h2><p class="mx-auto mt-4 max-w-[680px] text-base leading-7 text-mid-gray sm:text-lg sm:leading-8">Talk to TXA about Virtual Concierge initiatives for your destination.</p><a href="<?php echo esc_url(home_url('/destinations/pricing/')); ?>" class="mt-6 inline-flex min-h-12 w-full items-center justify-center rounded-lg bg-brand px-6 py-3 font-bold text-white !no-underline sm:mt-7 sm:w-auto sm:px-8">View Destination Packages</a></div></section>
</article>
<?php get_footer();
