<?php
/**
 * Template Name: Destination POI & Experiences
 * @package TailPress
 */
get_header();
$features=[['Create a richer destination layer','Build and maintain points of interest, experiences and visitor-ready content in one structured destination ecosystem.'],['Support local operators','Help tourism businesses become more discoverable and digitally ready across destination channels.'],['Reuse content everywhere','Use destination content across websites, campaigns, trade tools and visitor experiences instead of rebuilding it for each channel.'],['Keep content current','Maintain a cleaner source of destination information that can evolve with products, places and local priorities.']];
?>
<article class="bg-white text-near-black [font-family:'Source_Sans_Pro',sans-serif]">
<section class="px-4 py-8 lg:px-5"><div class="relative mx-auto min-h-[560px] max-w-[1360px] overflow-hidden rounded-2xl"><img src="https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=2200&q=85" alt="Destination landscape and visitor experience" class="absolute inset-0 h-full w-full object-cover"><div class="absolute inset-0 bg-near-black/45"></div><div class="relative z-10 flex min-h-[560px] items-center px-6 py-16 lg:px-8"><div class="max-w-[760px]"><p class="inline-flex rounded-lg bg-brand px-4 py-2 text-sm font-bold text-white">SMART DESTINATION</p><h1 class="mt-5 [font-family:'Hanken_Grotesk',sans-serif] text-4xl font-semibold leading-tight text-white sm:text-5xl lg:leading-[56px]">POI &amp; Experiences</h1><p class="mt-5 max-w-[670px] text-lg font-semibold leading-[30px] text-white">Create a stronger digital foundation for your destination by bringing places, experiences and local tourism content into a structured, reusable destination layer.</p><a href="<?php echo esc_url(home_url('/request-demo/')); ?>" class="mt-7 inline-flex rounded-lg bg-white px-8 py-3 text-lg font-bold text-brand !no-underline">Request Demo</a></div></div></div></section>
<section class="px-4 py-14 lg:px-16 lg:py-20"><div class="mx-auto max-w-[1312px]"><p class="text-sm uppercase text-brand">Destination content activation</p><h2 class="mt-3 max-w-[780px] text-3xl font-bold text-[#151c27] lg:text-4xl">Turn local tourism assets into connected digital content</h2><p class="mt-5 max-w-[800px] text-lg leading-8 text-mid-gray">POI &amp; Experiences gives destination organisations a practical way to structure the local visitor economy around places, products and experiences that can be activated across multiple digital channels.</p><div class="mt-10 grid gap-6 md:grid-cols-2"><?php foreach($features as $item): ?><article class="rounded-2xl border border-[#dfc0ba]/30 p-8 shadow-sm"><span class="flex size-10 items-center justify-center rounded-lg bg-brand-tint font-bold text-brand">+</span><h3 class="mt-5 text-xl font-semibold text-[#151c27]"><?php echo esc_html($item[0]); ?></h3><p class="mt-3 leading-7 text-mid-gray"><?php echo esc_html($item[1]); ?></p></article><?php endforeach; ?></div></div></section>
<section class="bg-surface px-4 py-14 lg:px-16"><div class="mx-auto grid max-w-[1312px] gap-10 rounded-2xl bg-white p-8 lg:grid-cols-2 lg:items-center lg:p-12"><div><h2 class="text-3xl font-bold text-[#151c27]">Built to power the rest of your Smart Destination tools</h2><p class="mt-5 text-base leading-7 text-mid-gray">Your POI and experience content becomes the reusable foundation for destination websites, microsites, trade portals, virtual concierge experiences and future campaigns.</p><a href="<?php echo esc_url(home_url('/destinations/')); ?>" class="mt-7 inline-flex rounded-lg bg-brand px-7 py-3 font-bold text-white !no-underline">Explore Smart Destinations</a></div><div class="grid grid-cols-2 gap-4"><?php foreach(['Destination Website','Microsite Campaigns','Trade Portal','Virtual Concierge'] as $label): ?><div class="rounded-xl border border-line bg-surface p-6 text-center font-semibold text-[#151c27]"><?php echo esc_html($label); ?></div><?php endforeach; ?></div></div></section>
</article>
<?php get_footer();
