<?php
/**
 * Template Name: Destination POI & Experiences
 * @package TailPress
 */
get_header();
$features=[['Create a richer destination layer','Build and maintain points of interest, experiences and visitor-ready content in one structured destination ecosystem.'],['Support local operators','Help tourism businesses become more discoverable and digitally ready across destination channels.'],['Reuse content everywhere','Use destination content across websites, campaigns, trade tools and visitor experiences instead of rebuilding it for each channel.'],['Keep content current','Maintain a cleaner source of destination information that can evolve with products, places and local priorities.']];
?>
<article class="bg-white text-near-black [font-family:'Source_Sans_Pro',sans-serif]">
<section class="px-4 py-6 sm:py-8 lg:px-5"><div class="relative mx-auto min-h-[460px] max-w-[1360px] overflow-hidden rounded-2xl sm:min-h-[520px] lg:min-h-[560px]"><img src="https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=2200&q=85" alt="Destination landscape and visitor experience" class="absolute inset-0 h-full w-full object-cover"><div class="absolute inset-0 bg-near-black/55 sm:bg-near-black/45"></div><div class="relative z-10 flex min-h-[460px] items-center px-6 py-14 sm:min-h-[520px] sm:px-8 sm:py-16 lg:min-h-[560px]"><div class="max-w-[760px]"><p class="inline-flex rounded-lg bg-brand px-4 py-2 text-xs font-bold text-white sm:text-sm">SMART DESTINATION</p><h1 class="mt-4 [font-family:'Hanken_Grotesk',sans-serif] text-3xl font-semibold leading-[1.1] text-white sm:mt-5 sm:text-5xl lg:leading-[56px]">POI &amp; Experiences</h1><p class="mt-4 max-w-[670px] text-base font-semibold leading-7 text-white sm:mt-5 sm:text-lg sm:leading-[30px]">Create a stronger digital foundation for your destination by bringing places, experiences and local tourism content into a structured, reusable destination layer.</p><a href="<?php echo esc_url(home_url('/request-demo/')); ?>" class="mt-6 inline-flex min-h-12 w-full items-center justify-center rounded-lg bg-white px-6 py-3 text-base font-bold text-brand !no-underline sm:mt-7 sm:w-auto sm:px-8 sm:text-lg">Request Demo</a></div></div></div></section>
<section class="px-4 py-12 sm:py-14 lg:px-16 lg:py-20"><div class="mx-auto max-w-[1312px]"><p class="text-xs uppercase text-brand sm:text-sm">Destination content activation</p><h2 class="mt-3 max-w-[780px] text-3xl font-bold leading-tight text-[#151c27] lg:text-4xl">Turn local tourism assets into connected digital content</h2><p class="mt-4 max-w-[800px] text-base leading-7 text-mid-gray sm:mt-5 sm:text-lg sm:leading-8">POI &amp; Experiences gives destination organisations a practical way to structure the local visitor economy around places, products and experiences that can be activated across multiple digital channels.</p><div class="mt-8 grid gap-5 sm:mt-10 md:grid-cols-2 md:gap-6"><?php foreach($features as $item): ?><article class="rounded-2xl border border-[#dfc0ba]/30 p-6 shadow-sm sm:p-8"><span class="flex size-10 items-center justify-center rounded-lg bg-brand-tint font-bold text-brand">+</span><h3 class="mt-5 text-xl font-semibold text-[#151c27]"><?php echo esc_html($item[0]); ?></h3><p class="mt-3 text-sm leading-6 text-mid-gray sm:text-base sm:leading-7"><?php echo esc_html($item[1]); ?></p></article><?php endforeach; ?></div></div></section>
<section class="bg-surface px-4 py-12 sm:py-14 lg:px-16"><div class="mx-auto grid max-w-[1312px] gap-8 rounded-2xl bg-white p-6 sm:p-8 lg:grid-cols-2 lg:items-center lg:gap-10 lg:p-12"><div><h2 class="text-3xl font-bold leading-tight text-[#151c27]">Built to power the rest of your Smart Destination tools</h2><p class="mt-4 text-base leading-7 text-mid-gray sm:mt-5">Your POI and experience content becomes the reusable foundation for destination websites, microsites, trade portals, virtual concierge experiences and future campaigns.</p><a href="<?php echo esc_url(home_url('/destinations/')); ?>" class="mt-6 inline-flex min-h-12 w-full items-center justify-center rounded-lg bg-brand px-6 py-3 font-bold text-white !no-underline sm:mt-7 sm:w-auto sm:px-7">Explore Smart Destinations</a></div><div class="grid grid-cols-1 gap-3 sm:grid-cols-2 sm:gap-4"><?php foreach(['Destination Website','Microsite Campaigns','Trade Portal','Virtual Concierge'] as $label): ?><div class="rounded-xl border border-line bg-surface p-5 text-center text-sm font-semibold text-[#151c27] sm:p-6 sm:text-base"><?php echo esc_html($label); ?></div><?php endforeach; ?></div></div></section>
</article>
<?php get_footer();
